In [7]:
# Importando bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt

# Carregando dados do catálogo Hipparcos

column_names = ["HIP", "RArad", "DErad", "Plx", "e_Plx", "BV", "e_BV", "Vmag"]
hipparcos_data = pd.read_csv("vizier_votable2.csv", sep=';', header=None, names=column_names, usecols=[1, 8, 9, 13, 14, 16, 17, 19])

C:\Users\ronal\AppData\Local\Temp\ipykernel_22228\3268759092.py:8: FutureWarning: Defining usecols with out of bounds indices is deprecated and will raise a ParserError in a future version.
  hipparcos_data = pd.read_csv("vizier_votable2.csv", sep=';', header=None, names=column_names, usecols=[1, 8, 9, 13, 14, 16, 17, 19])

                  HIP  RArad   DErad     Plx e_Plx   BV e_BV Vmag
0        10520.431502   3.54   -5.20       1   NaN  NaN  NaN  NaN
1      -192955.822955  21.90  181.21       2   NaN  NaN  NaN  NaN
2       385133.404425   2.81    5.24       3   NaN  NaN  NaN  NaN
3      -515336.764631   7.75   62.85       4   NaN  NaN  NaN  NaN
4      -403528.328477   2.87    2.53       5   NaN  NaN  NaN  NaN
...               ...    ...     ...     ...   ...  ...  ...  ...
118213  114025.369463   1.92   -2.16  118214   NaN  NaN  NaN  NaN
118214 -222541.208191  10.63  148.74  118215   NaN  NaN  NaN  NaN
118215   55723.587771   5.00   20.92  118216   NaN  NaN  NaN  NaN
118216 -642220.328377  19.22  216.99  118217   NaN  NaN  NaN  NaN
118217 -653437.675251   8.71   48.63  118218   NaN  NaN  NaN  NaN

[118218 rows x 8 columns]